### ISSUE TITLE
The Memory Keeper

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#10]
display the amount of memory kept

**Comment by EnakxD** [comment]
This code creates a button labeled "Stored Memory" each time createMemory() is called. When the button is clicked, it logs "Memory accessed..." to the console. The function also increments a memoryCount variable to track the number of memories created and calls updateMemoryDisplay() to update the text in an HTML element with id="memory-display", showing the total memories stored. The display element should be added to the HTML with 
Memories Stored: 0

**Comment by rishicds** [comment]
assigned
