### ISSUE TITLE
Remove the pesky bugs on screen

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#13]

**Comment by CodeMasterCSE** [comment]
Removed all the insects floating in the screen 
![Removed insects](https://github.com/user-attachments/assets/0b26d3d4-1b96-4cd1-86dd-97dd93cc4c24)

**Comment by rishicds** [comment]
Nice! Assigned

**Comment by omsohom01** [comment]
.insect {
    width: 30px;
    height: 30px;
    background-image: url('https://cdn-icons-png.flaticon.com/512/10771/10771520.png'); 
    background-size: contain;
    background-repeat: no-repeat;
    position: absolute;
    top: 0;
    left: 0;
    animation: floatBug 10s linear infinite;
    pointer-events: none;
}

@keyframes floatBug {
    0% { transform: translate(0, 0); }
    25% { transform: translate(80vw, 10vh); }
    50% { transform: translate(40vw, 60vh); }
    75% { transform: translate(20vw, 30vh); }
    100% { transform: translate(0, 0); }
}

please remove this part from css and

const numberOfBugs = 5; 
let viewportHeight = window.innerHeight;
let viewportWidth = window.innerWidth;

function createBug() {
    const bug = document.createElement('div');
    bug.classList.add('insect');

    
    bug.style.top = `${Math.random() * viewportHeight}px`;
    bug.style.left = `${Math.random() * viewportWidth}px`;

    bug.style.animationDelay = `${Math.random() * 5}s`;

    document.body.appendChild(bug);

    
    setInterval(() => {
        bug.style.top = `${Math.random() * viewportHeight}px`;
        bug.style.left = `${Math.random() * viewportWidth}px`;
    }, 3000 + Math.random() * 2000); 
}

for (let i = 0; i < numberOfBugs; i++) {
    createBug();
}

and this part of js 

this will remove the bugs

**Comment by rishicds** [comment]
hello @omsohom01 this has been assigned to @CodeMasterCSE , if he doesnt give any PRs by 3rd Nov you can work on this

**Comment by CodeMasterCSE** [comment]
assign him the issue.

**Comment by rishicds** [comment]
Assigned @omsohom01

**Comment by omsohom01** [comment]
how to pull request???

**Comment by omsohom01** [comment]
dada, your number??

**Comment by 0M4NU4L** [comment]
@omsohom01 You can find his number in the official GDG group on whatsapp.
