### ISSUE TITLE
Find the hidden message

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#14]
There is a hidden message in the website, find it and you will go up the leaderboard

**Comment by 0M4NU4L** [comment]
Method 1:

Upon inspection of the code(script.js), we can use console.debug command to print each step and identify the hidden message.

```
console.debug
console.debug('debug')  
console.debug('quest')  
console.debug('decrypt')
```

Method 2:

Manually decoding the base64 code using any online decoder. Found in index.html

**Comment by rishicds** [comment]
Yes method 1 is the correct approach,assigned. All the best!
