### ISSUE TITLE
Find the hidden flag

### ISSUE THREAD

**Issue by Anirban-Majumder** [GDSC-RCCIIT/debug-quest#26]
There is a hidden message in the lv2 website, find it and you will go up the leaderboard.
Hint open dev tools.

**Comment by Prattaykun** [comment]
data-part1="Y29uZ3JhdHVsYXRpb25z"
         data-part2="eW91IGFyZSBh"
         data-part3="Z3JlYXQgZGV2ZWxvcGVy" this part in index.html file has the message encoded in base64
         
         in script.js there's a decodeMessage function which should decode the 3 parts using atob but when i tried on console it showed me error, so i decoded the encoded message on a decoder and found the message to be "congratulations you are a great developer"
![Screenshot 2024-11-02 093534](https://github.com/user-attachments/assets/b7b8864d-609e-4121-9d7f-dd2dc22c68e5)
![Screenshot 2024-11-01 230239](https://github.com/user-attachments/assets/0babe76b-1c08-47ea-a7e4-0427bf78a528)

**Comment by rishicds** [comment]
@Anirban-Majumder let us know if he decoded your flag correctly

**Comment by Anirban-Majumder** [comment]
@Prattaykun Correct flag

**Comment by rishicds** [comment]
Congratulations @Prattaykun!
