### ISSUE TITLE
Remove Unnecessary Promotion

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#3]
GDG RCCIIT is a very well known club which doesn't require constant promotion, remove the popup banner that appears every few seconds.
![image](https://github.com/user-attachments/assets/fb5e68b1-a713-4aca-9f3c-c2aa2bc890a3)

**Comment by CodeMasterCSE** [comment]
Removed the promotion banner.
![Removed unwanted faces and banner](https://github.com/user-attachments/assets/342520d9-3753-48ee-9dbe-48252afc17a4)

**Comment by rishicds** [comment]
Good, assigned
