### ISSUE TITLE
Vanishing Act 

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#4]
Fix it so when clicked the button displays "I solved this bug and got nothing"

**Comment by CodeMasterCSE** [comment]
The issue is solved and displays the given message in place of the button
![The Vanishing Act solved](https://github.com/user-attachments/assets/46e34a9b-ddbd-4d9b-9a99-8bc85d1d1c31)

**Comment by Pragya79645** [comment]
solve me button error fixed

**Comment by rishicds** [comment]
Assigned

**Comment by Pragya79645** [comment]
removed the onclick event

**Comment by Pragya79645** [comment]
removed the onclick event
