### ISSUE TITLE
Window prompt on site load

### ISSUE THREAD

**Issue by Pragya79645** [GDSC-RCCIIT/debug-quest#40]
the window prompt can be removed by eliminating the window.onload event.

**Comment by EnakxD** [comment]
// Remove or comment out the window.onload event
// window.onload = function() {
//     window.prompt("Welcome to the site! Click OK to continue.");
// };

**Comment by rishicds** [comment]
@EnakxD create your own issue please, rules were changed so this time, you find the bugs and make an issue, follow this issue format

Title
Issue description 
How to fix
Photo(optional)
