### ISSUE TITLE
The Disturbance Code fix

### ISSUE THREAD

**Issue by Neutral-Ronnie** [GDSC-RCCIIT/debug-quest#41]
Issue: Clicking the button triggers blue screen 
Fix: Removing/modifying triggerDisturbance(), moveCardAround(), playAmogus()

**Comment by EnakxD** [comment]
function triggerDisturbance() {
    const body = document.body;

    // Remove or comment out the following line to avoid the blue screen.
    // moveCardAround();

    // Remove or comment out the call to playAmogus() to avoid it being played here.
    // playAmogus(); 

    // Only update the disturbance text and make the hidden message visible.
    const hiddenMessage = document.getElementById("hidden-disturbance");
    hiddenMessage.classList.remove("hidden-message"); // Make the message visible
}
