### ISSUE TITLE
The Ghostly Revelation fix

### ISSUE THREAD

**Issue by 0M4NU4L** [GDSC-RCCIIT/debug-quest#43]
Issue: Triggers multiple images along with a sound and the card disappears from sight.

Information: The card consists of two functions `improveVanishingAct()` and `playEerieSound()`. The function `improveVanishingAct()` triggers an array of images along with a sound. Lastly makes the card disappear from sight. Upon clicking in the blank area it triggers the function `playEerieSound()` again.

Fix: Removing both the functions will fix the issue.

**Comment by rishicds** [comment]
already assigned to someone else, please create another issue
