### ISSUE TITLE
The Counters Tale

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#5]
1+1 should equal 2 not 11,fix it

**Comment by Pragya79645** [comment]
i want to work on this

**Comment by Pragya79645** [comment]
We can fix the bug by incrementing like this

<button class="action-btn" onclick="document.getElementById('points').innerHTML = parseInt(document.getElementById('points').innerHTML) + 1">
        Count Up
    </button>

Currently it's appending so it becomes 1111

**Comment by Pragya79645** [comment]
We can fix the bug by incrementing like this

<button class="action-btn" onclick="document.getElementById('points').innerHTML = parseInt(document.getElementById('points').innerHTML) + 1">
        Count Up
    </button>

Currently it's appending so it becomes 1111

**Comment by Pragya79645** [comment]
We can fix the bug by incrementing like this

"<button class="action-btn" onclick="document.getElementById('points').innerHTML = parseInt(document.getElementById('points').innerHTML) + 1">
        Count Up
    </button>"

Currently it's appending so it becomes 1111

**Comment by Pragya79645** [comment]
I'll use parseInt to make sure it's a number and gets incremented correctly

**Comment by rishicds** [comment]
That's a good approach, assigned
