### ISSUE TITLE
Tap If You Dare fix

### ISSUE THREAD

**Issue by CodeMasterCSE** [GDSC-RCCIIT/debug-quest#68]
Issue: Clicking the button displays a message "FATAL ERROR! SYSTEM CRASHED!" with a blue background and shaking effect and a horrifying background sound.
Solution: Modify the js file to show an appropiate message on clicking the button.
![solved](https://github.com/user-attachments/assets/da45e22e-78d1-4a85-9115-eee76e745eb3)

**Comment by rishicds** [comment]
Assigned
