### ISSUE TITLE
Spinning Emoji issue fix

### ISSUE THREAD

**Issue by Sampurnasit** [GDSC-RCCIIT/debug-quest#69]
Issue: Fun chaotic emojis were spinning in the top of the card 🤪 The Bouncing Bamboozler.
Fix: Removing the `spin` animation from the `chaotic` id in the css file.
![Screenshot_14-11-2024_205610_127 0 0 1](https://github.com/user-attachments/assets/8bf9a4d9-92ac-490b-8e1e-b8a88c59a7bf)

**Comment by rishicds** [comment]
Assigned
