### ISSUE TITLE
The Echo Chamber

### ISSUE THREAD

**Issue by rishicds** [GDSC-RCCIIT/debug-quest#8]
Besides giving unnecessary popups it also crashes the site after 20 minutes, fix it

**Comment by Pragya79645** [comment]
i want to work upon this

**Comment by Pragya79645** [comment]
removing the alerts will fix the bug

**Comment by Pragya79645** [comment]
removing the alerts will fix the bug
![pic](https://github.com/user-attachments/assets/f6046c72-c85d-458d-94c0-aecb0926ed04)
